### ISSUE TITLE
Imports in registry content is not resolved when the file is not exists in disk

### ISSUE THREAD

**Issue by weizhenye** [reactway/scss-bundle#76] opened 2019-10-01 13:01 UTC
**Describe the bug**
I'm writing a rollup plugin to bundle scss in [`.vue` files](https://vue-loader.vuejs.org/spec.html#intro) and I'm using JS API of `scss-bundle`.

For a Vue SFC like `/path/to/Example.vue`, I can get scss content in this file and generate a id like `/path/to/Example.vue.0.scss`. I don't want to write it to disk for it may confuse user and cause unexpected problems, so I pass it as registry to `scss-bundle`. However `@import` in registry content is not resolved.

**To Reproduce**

Suppose there are two files in disk:

```scss
// /path/to/index.scss
@import "/path/to/not-exists-in-disk.scss";
```
```scss
// /path/to/foo.scss
.foo {}
```

 And run with following code:

```js
// /path/to/index.js
const { Bundler } = require('scss-bundle');
(async () => {
  const bundler = new Bundler({
    '/path/to/not-exists-in-disk.scss': '@import "./foo.scss";'
  });
  const result = await bundler.bundle('/path/to/index.scss');
  console.log(result.bundledContent);
  // > @import "./foo.scss";
})();
```

`@import "./foo.scss";` is not resolved and is outputted directly.

**Expected behavior**
Imports in registry content can be resolved even if the file is not exists in disk.

**Package version:** v3.0.1
**Node version:** v12.11.0
**OS:** Mac OS

**Comment by MartynasZilinskas** [comment] 2019-10-07 12:31
Hey @weizhenye, thanks for filling an issue.  The problem is in this part: https://github.com/reactway/scss-bundle/blob/master/src/bundler.ts#L138-L156

At this time, I can't find an elegant solution without making breaking changes. So any help appreciated.

**Comment by MartynasZilinskas** [comment] 2019-10-24 17:29
Package is released as ` @canary`.

```
$ npm install scss-bundle@0.0.0-canary.048dc82
```

**Comment by MartynasZilinskas** [comment] 2019-11-16 19:55
Package is released as `@latest`.
```
$ npm install scss-bundle@3.0.2
```

**Closed by MartynasZilinskas** 2019-11-16 19:55 UTC
Labels: bug, help wanted
